services:

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: dev
    container_name: lushink_app
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  web:
    image: nginx:1.27-alpine
    container_name: lushink_web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  vite:
    image: node:20-alpine
    container_name: lushink_vite
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"

  db:
    image: mysql:8.0
    container_name: lushink_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: lushink
      MYSQL_USER: lushink
      MYSQL_PASSWORD: lushink
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: